name: sleep 2 minutes

on: [workflow_dispatch, pull_request]

jobs:
  build:
    name: Display Platform Info
    runs-on: ubuntu-20.04-ppc64le
    
    steps:
      - uses: action/checkout@v3
      
      - name: Print System Info
        run: |
          uname -a
          arch
