name: sleep 2 minutes

on: [workflow_dispatch, pull_request]

jobs:
  print-info:
    name: Display Platform Info
    #runs-on:  ubuntu-latest
    runs-on: ubuntu-20.04-ppc64le
    steps:
      - name: Print System Info
        run: |
          uname -a
          arch
      - name: Pause for 35s
        run: sleep 2m
