# name: checkout  repo

# on: [workflow_dispatch]

# jobs:
#   basic-checkout:
#     runs-on: ubuntu-20.04-ppc64le
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
name: checkout repo

on: [workflow_dispatch]

jobs:
  print-info:
    name: Display Platform Info
    runs-on: ubuntu-20.04-ppc64le
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: print system info
        run: |
          uname -a
          arch
      - name: print messege
        run: echo "successful!!"
