name: hello message 1  

on: [workflow_dispatch]

jobs:
  print-info:
    name: Display Platform Info 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print System Info
        run: |
          uname -a
          arch
      - name: Hello messge
        run: echo "Hello welcome!"
      - name: list files
        run: ls
