name: node-action-example

on: [workflow_dispatch, push]

jobs:
  node-action-example:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: adilhusain-s/setup-node@main
        with:
          node-version: 20
      - run: npm install
