name: node-action-example

on: [workflow_dispatch]

jobs:
  node-action-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: adilhusain-s/setup-node@main
        with:
          node-version: 20
      - run: npm install
