name: python-action-example

on:
  workflow_dispatch:
  push:

jobs:
  python-action-example:
    runs-on: ubuntu-20.04-ppc64le
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: python runner-info.py
